#! /bin/sh

wid=$1
class=$2
instance=$3
consequences=$4
title=$(xtitle "$wid")


main () {
case "$class" in
	mpv)
	    eval "$consequences"
		[ "$state" ] || echo "state=floating focus=on center=on rectangle=925x519+0+0 border=off"
		;;
	Viewnior)
	    eval "$consequences"
	    [ "$state" ] || echo "state=floating focus=on center=on border=off"
		;;
	whatsapp-nativefier-d40211|TelegramDesktop)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^4 center=on follow=on rectangle=930x617+0+0"
		;;
	retroarch)
	    eval "$consequences"
	    [ "$state" ] || echo "state=pseudo_tiled desktop=^6 center=on follow=on border=off"
	    ;;
	Pavucontrol)
	    eval "$consequences"
	    [ "$state" ] || echo "state=floating follow=on center=on"
	    ;;
	Virt-manager)
	    eval "$consequences"
	    [ "$state" ] || echo "state=floating desktop=^5 follow=on center=on"
	    ;;
	 Transmission-gtk)
	    eval "$consequences"
	    [ "$state" ] || echo "desktop=^6 follow=on"
	    ;;
		"")
        sleep 0.5
		wm_class=($(xprop -id $wid | grep "WM_CLASS" | grep -Po '"\K[^,"]+'))
		class=${wm_class[-1]}
		[[ ${#wm_class[@]} == "2" ]] && instance=${wm_class[0]}
		[[ -n "$class" ]] && main
		;;
esac
}

main
case "$instance" in
     Toolkit)
        eval "$consequences"
        [ "$state" ] || echo "state=floating sticky=on rectangle=500x290+1054+593"
	    ;;
esac  
